// <auto-generated />
namespace CodingApe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SQLSectionList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SQLSectionList));
        
        string IMigrationMetadata.Id
        {
            get { return "201906150405537_SQLSectionList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
